import React, { useCallback, useEffect, useMemo, useState } from 'react';
const API = import.meta.env.VITE_API_URL || 'http://localhost:4000';
export default function Devices({ token }) {
  const [devices,setDevices]=useState([]),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(`${API}/api/devices`,{headers:token?{Authorization:`Bearer ${token}`}:{}});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load devices');setDevices(b.devices||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[token]);
  useEffect(()=>{load()},[load]);
  async function sync(){setSyncing(true);setError('');try{const r=await fetch(`${API}/api/integrations/scalefusion/sync`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{}});const b=await r.json();if(!r.ok)throw new Error(b.error||'Scalefusion sync failed');await load()}catch(e){setError(e.message)}finally{setSyncing(false)}}
  const filtered=useMemo(()=>devices.filter(d=>{const q=search.toLowerCase();const match=!q||[d.name,d.serial_number,d.user_name,d.os,d.os_version,d.mdm_source].some(v=>String(v||'').toLowerCase().includes(q));return match&&(status==='all'||String(d.status||'').toLowerCase()===status)}),[devices,search,status]);
  const healthy=devices.filter(d=>/compliant|online|active/i.test(d.status||'')).length,risk=devices.filter(d=>/risk|offline|non/i.test(d.status||'')).length;
  return <section className="devices-page"><div className="devices-head"><div><p className="eyebrow">ENDPOINT MANAGEMENT</p><h1>Devices</h1><p className="muted">Live Mac inventory synchronized from Scalefusion.</p></div><button onClick={sync} disabled={syncing}>{syncing?'Syncing…':'Sync Scalefusion'}</button></div><div className="device-stats"><div><span>Total Macs</span><b>{devices.length}</b></div><div><span>Healthy</span><b>{healthy}</b></div><div><span>Needs attention</span><b>{risk}</b></div></div>{error&&<div className="device-error">{error}</div>}<div className="device-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search device, serial, user or macOS…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="compliant">Compliant</option><option value="online">Online</option><option value="active">Active</option><option value="at risk">At Risk</option><option value="offline">Offline</option></select><span>{filtered.length} devices</span></div><div className="device-table-wrap"><table><thead><tr><th>Device</th><th>Serial number</th><th>User</th><th>macOS</th><th>Status</th><th>Last seen</th><th>Source</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="empty">Loading Scalefusion inventory…</td></tr>:filtered.length===0?<tr><td colSpan="7" className="empty">No devices found. Run a Scalefusion sync or change your filters.</td></tr>:filtered.map(d=><tr key={d.id||d.external_id}><td><strong>{d.name||'Unnamed Mac'}</strong><small>{d.external_id||'—'}</small></td><td>{d.serial_number||'—'}</td><td>{d.user_name||d.user?.name||'Unassigned'}</td><td>{[d.os,d.os_version].filter(Boolean).join(' ')||'—'}</td><td><span className="device-status">{d.status||'Unknown'}</span></td><td>{d.last_seen_at?new Date(d.last_seen_at).toLocaleString():'—'}</td><td>{d.mdm_source||'Scalefusion'}</td></tr>)}</tbody></table></div></section>;
}