import React,{useEffect,useMemo,useRef,useState}from'react';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000';
const EMPTY={name:'',email:'',department:'',jobTitle:'',managerEmail:'',startDate:''};
export default function Users({token}){
 const[data,setData]=useState([]),[q,setQ]=useState(''),[dept,setDept]=useState('All'),[showAdd,setShowAdd]=useState(false),[showBulk,setShowBulk]=useState(false),[form,setForm]=useState(EMPTY),[bulk,setBulk]=useState([]),[message,setMessage]=useState('');const fileRef=useRef();
 const headers=token?{Authorization:`Bearer ${token}`}:{},load=()=>fetch(`${API}/api/users`,{headers}).then(r=>r.json()).then(x=>setData(x.users||[])).catch(()=>setData([]));useEffect(load,[token]);
 const departments=useMemo(()=>['All',...new Set(data.map(u=>u.department).filter(Boolean))],[data]);
 const filtered=data.filter(u=>(dept==='All'||u.department===dept)&&`${u.name||''} ${u.email||''} ${u.department||''}`.toLowerCase().includes(q.toLowerCase()));
 const submit=async e=>{e.preventDefault();setMessage('');const r=await fetch(`${API}/api/users`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(form)});const x=await r.json().catch(()=>({}));if(!r.ok){setMessage(x.error||'Could not add user');return}setForm(EMPTY);setShowAdd(false);setMessage('User added');load()};
 const parseCSV=file=>{const rd=new FileReader();rd.onload=()=>{const lines=String(rd.result).split(/\r?\n/).filter(Boolean),h=lines.shift().split(',').map(x=>x.trim().toLowerCase());setBulk(lines.map(line=>{const v=line.split(',').map(x=>x.trim()),o={};h.forEach((k,i)=>o[k]=v[i]||'');return{name:o.name||o['full name'],email:o.email,department:o.department,jobTitle:o['job title']||o.jobtitle,managerEmail:o['manager email']||o.manageremail,startDate:o['start date']||o.startdate}}).filter(x=>x.name&&x.email&&x.department))};rd.readAsText(file)};
 const importBulk=async()=>{const r=await fetch(`${API}/api/users/bulk`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({users:bulk})});const x=await r.json().catch(()=>({}));if(!r.ok){setMessage(x.error||'Bulk import failed');return}setMessage(`${x.created||0} users imported`);setBulk([]);setShowBulk(false);load()};
 return <section className="pagePanel userAdmin"><div className="pageTitle"><div><h2>User Admin</h2><p>Manage people, departments, device assignments and activity access.</p></div><div className="userActions"><button className="filter" onClick={()=>setShowBulk(!showBulk)}>⇧ Bulk upload</button><button onClick={()=>setShowAdd(!showAdd)}>＋ Add new user</button></div></div>{message&&<div className="banner">{message}</div>}
 <div className="cards userKpis"><div className="metricCard"><span>Total Users</span><strong>{data.length}</strong><small>directory</small></div><div className="metricCard"><span>Active Users</span><strong>{data.filter(x=>x.active!==false).length}</strong><small>enabled</small></div><div className="metricCard"><span>Departments</span><strong>{Math.max(0,departments.length-1)}</strong><small>teams</small></div><div className="metricCard"><span>Assigned Devices</span><strong>{data.filter(x=>x.device).length}</strong><small>mapped</small></div></div>
 {showAdd&&<form className="userForm" onSubmit={submit}><h3>Add New User</h3><div className="formGrid">{[['name','Full Name'],['email','Work Email'],['department','Department'],['jobTitle','Job Title'],['managerEmail','Manager Email'],['startDate','Start Date']].map(([k,l])=><label key={k}><span>{l}{['name','email','department'].includes(k)?' *':''}</span><input type={k==='email'||k==='managerEmail'?'email':k==='startDate'?'date':'text'} required={['name','email','department'].includes(k)} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="userActions"><button type="button" className="filter" onClick={()=>setShowAdd(false)}>Cancel</button><button type="submit">Create User</button></div></form>}
 {showBulk&&<div className="userForm"><h3>Bulk Upload Users</h3><p>CSV required columns: <b>Name, Email, Department</b>. Optional: Job Title, Manager Email, Start Date. Maximum 500 users per upload.</p><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={e=>e.target.files[0]&&parseCSV(e.target.files[0])}/>{bulk.length>0&&<><p><b>{bulk.length}</b> valid users ready to import.</p><div className="bulkPreview">{bulk.slice(0,8).map((u,i)=><div key={i}><b>{u.name}</b><span>{u.email}</span><span>{u.department}</span></div>)}</div><button onClick={importBulk}>Import {bulk.length} Users</button></>}</div>}
 <div className="userToolbar"><input placeholder="Search name, email or department…" value={q} onChange={e=>setQ(e.target.value)}/><select value={dept} onChange={e=>setDept(e.target.value)}>{departments.map(x=><option key={x}>{x}</option>)}</select></div><div className="table"><div className="thead"><span>User</span><span>Department</span><span>Job Title</span><span>Device</span><span>Status</span></div>{filtered.map(u=><div className="trow" key={u.id}><span><b>{u.name}</b><small>{u.email}</small></span><span>{u.department||'Unassigned'}</span><span>{u.job_title||'—'}</span><span>{u.device||'—'}</span><span className="badge good">{u.active===false?'Inactive':u.status||'Active'}</span></div>)}{!filtered.length&&<div className="emptyUsers">No users match this view.</div>}</div></section>
}